'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Cfg_CodigoObjeto|Tag,Cfg_DescObjeto|Cfg_DescObjeto,Cfg_NumeroSensor|")>  _
        Public Property AloneAttributes() As String
            Get
                Return CType(Me("AloneAttributes"),String)
            End Get
            Set
                Me("AloneAttributes") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Cfg_Mapeado|Field Attribute")>  _
        Public Property ArrayAttributes() As String
            Get
                Return CType(Me("ArrayAttributes"),String)
            End Get
            Set
                Me("ArrayAttributes") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Instancia")>  _
        Public Property InstanceNameIndex() As String
            Get
                Return CType(Me("InstanceNameIndex"),String)
            End Get
            Set
                Me("InstanceNameIndex") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Template")>  _
        Public Property InstanceTemplateIndex() As String
            Get
                Return CType(Me("InstanceTemplateIndex"),String)
            End Get
            Set
                Me("InstanceTemplateIndex") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SEÑALES (Tags en el driver)")>  _
        Public Property CSVTAGS() As String
            Get
                Return CType(Me("CSVTAGS"),String)
            End Get
            Set
                Me("CSVTAGS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("DIRECCION PLC")>  _
        Public Property CSVDir() As String
            Get
                Return CType(Me("CSVDir"),String)
            End Get
            Set
                Me("CSVDir") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Field Attribute")>  _
        Public Property InstanceEngUnits1() As String
            Get
                Return CType(Me("InstanceEngUnits1"),String)
            End Get
            Set
                Me("InstanceEngUnits1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Unidades")>  _
        Public Property InstanceEngUnits2() As String
            Get
                Return CType(Me("InstanceEngUnits2"),String)
            End Get
            Set
                Me("InstanceEngUnits2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3")>  _
        Public Property UDAInt1() As String
            Get
                Return CType(Me("UDAInt1"),String)
            End Get
            Set
                Me("UDAInt1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3, 4, 5")>  _
        Public Property ScriptInt1() As String
            Get
                Return CType(Me("ScriptInt1"),String)
            End Get
            Set
                Me("ScriptInt1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute(".ConversionMode, .HiHi.Priority, .Hi.Priority, .Lo.Priority, .LoLo.Priority, .HiH"& _ 
            "i.DescAttrName, .Hi.DescAttrName, .Lo.DescAttrName, .LoLo.DescAttrName, .LevelAl"& _ 
            "arm.ValueDeadband, .LevelAlarm.TimeDeadband")>  _
        Public Property AnalogLockedAttr() As String
            Get
                Return CType(Me("AnalogLockedAttr"),String)
            End Get
            Set
                Me("AnalogLockedAttr") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute(".ActiveAlarmState, .DescAttrName, .BooleanAlarm.TimeDeadBand, .Category")>  _
        Public Property DiscreteLockedAttr() As String
            Get
                Return CType(Me("DiscreteLockedAttr"),String)
            End Get
            Set
                Me("DiscreteLockedAttr") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Nombre|1||2|||;Descripcion|1||4,5|.Desc||;AccessMode|3|Input,InputOutput,Output|3"& _ 
            "|.AccessMode||;Historizado|2||12,13|.Historized||;Evento|2||6,7|.LogDataChangeEv"& _ 
            "ent||;State Labels|4|Label False,Label True|8,9|.UseOffOnMsg|.OffMsg,.OnMsg|10,1"& _ 
            "1;Alarma|4|Prioridad|14,15|.Alarmed|.Priority|16;")>  _
        Public Property SettingPrueba() As String
            Get
                Return CType(Me("SettingPrueba"),String)
            End Get
            Set
                Me("SettingPrueba") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Nombre|1||2|||;Descripcion|1||4,5|.Desc||;Unidad|1||8,12|.EngUnits||;AccessMode|3"& _ 
            "|Input,InputOutput,Output|3|.AccessMode||;Data Type|3|Integer,Float,Double|3|.An"& _ 
            "alogType||;Historizado|2||18,19|.Historized||;Evento|2||6,7|.LogDataChangeEvent|"& _ 
            "|;IO Scalling|4|Raw Min,Raw Max,EU Min,Eu Max,EU Range Min,EU Range Max|10,11|.S"& _ 
            "caled|.RawMin,.RawMax,.EngUnitsMin,.EngUnitsMax,.EngUnitsRangeMin,.EngUnitsRange"& _ 
            "Max|12,15,13,16,14,17;Limit Alarms|4|HiHi,Hi,Lo,LoLo|20,21|.LevelAlarmed|.HiHi.L"& _ 
            "imit,.Hi.Limit,.Lo.Limit,.LoLo.Limit|22,24,26,28;")>  _
        Public Property SettingPrueba1() As String
            Get
                Return CType(Me("SettingPrueba1"),String)
            End Get
            Set
                Me("SettingPrueba1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LastGalaxy() As String
            Get
                Return CType(Me("LastGalaxy"),String)
            End Get
            Set
                Me("LastGalaxy") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.aaGRToolKit.My.MySettings
            Get
                Return Global.aaGRToolKit.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
